### PR TITLE
Bring back up to date

### PR DESCRIPTION
**Pull request by bitwalker**
@atabary If you would like, I can take over maintenance of this project so we can keep it in parity with timex. This PR brings things up to speed and bumps the minor version, just need to push a new release to hex :)

### CODE REVIEW

**Comment by atabary** [comment]
I just gave you push access to this repository, so feel free to commit!

**Comment by bitwalker** [comment]
Cheers @atabary! Would you also be willing to give me package management rights on hex.pm? You can do so with: `mix hex.owner add timex-interval paulschoenfelder@gmail.com`. If you'd prefer to be the sole person to push new releases, I'm totally cool with that, but I can help keep things moving when you're busy or unavailable if I'm able to push fixes and releases :)

As an alternative solution to maintaining this package independently, I'm also considering making intervals a standard part of timex, so if you'd be open to me merging your code into timex (with some alterations, but with you marked as author of course), that's another route we can take. Since this package is relatively lightweight it seems like a reasonable addition. That said, it's entirely up to you!

**Comment by requires** [comment]
@bitwalker: just gave you the rights to push things on hex.pm.

If you want to merge timex-interval into timex, go ahead! As long as I'm mentioned somewhere as author, it's perfectly fine by me. I just checked the licenses: I picked Apache2, but since timex is MIT and I like to keep things simple, you can consider timex-interval relicensed as MIT.

**Comment by bitwalker** [comment]
@atabary I've merged `timex-interval` in the following commit to `timex` (and pushed 1.0.0-pre). Please take a look when you get a chance and let me know if you think any changes are necessary! You're tagged as the author as well :)

https://github.com/bitwalker/timex/commit/6a2563d5e3aee5b614f22a93c84720152c4a6e62

**Comment by atabary** [comment]
Looks good to me!

**Pull request merged**
